import Link from "next/link";
import { getServerApiClient } from "@/utils/server-orpc";

export default async function MyReservationsPage() {
  const api = await getServerApiClient();
  const reservations = await api.reservations.listMine() as Record<string, unknown>[];
  if (!reservations.length) return <div className="rounded-2xl border border-dashed border-border p-10 text-center"><h2 className="font-semibold">No reservations yet</h2><p className="mt-2 text-sm text-muted-foreground">Choose an available plot from a verified estate.</p><Link href="/#explore-lands" className="mt-5 inline-flex h-11 items-center rounded-xl bg-primary px-5 text-sm font-medium text-primary-foreground">Explore estates</Link></div>;
  return <div className="grid gap-4">{reservations.map((reservation) => <article key={String(reservation.id)} className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">{String(reservation.estateName)}</p><h2 className="mt-1 text-lg font-semibold">Plot {String(reservation.plotNumber)}</h2></div><span className="rounded-full border border-border px-3 py-1 text-xs font-semibold">{String(reservation.status).replaceAll("_", " ")}</span></div><dl className="mt-5 grid grid-cols-2 gap-4 border-t border-border pt-4 text-sm"><div><dt className="text-muted-foreground">Reservation reference</dt><dd className="mt-1 font-semibold">{String(reservation.reference)}</dd></div><div><dt className="text-muted-foreground">Reserved price</dt><dd className="mt-1 font-semibold">GHS {Number(reservation.priceSnapshot).toLocaleString()}</dd></div></dl><div className="mt-5 flex flex-wrap gap-4">{["ACTIVE", "PAYMENT_PENDING"].includes(String(reservation.status)) ? <Link href={`/reservations/${String(reservation.reference)}/payment`} className="font-semibold text-primary underline underline-offset-4">{reservation.status === "ACTIVE" ? "Pay now" : "View payment"}</Link> : null}<Link href={`/estates/${String(reservation.estateSlug)}`} className="text-sm font-semibold underline underline-offset-4">View estate</Link></div></article>)}</div>;
}
