import Link from "next/link";
import { notFound } from "next/navigation";
import { getServerApiClient } from "@/utils/server-orpc";

export default async function ReservationCreatedPage({ params }: { params: Promise<{ reference: string }> }) {
  const { reference } = await params;
  const api = await getServerApiClient();
  let checkout: Record<string, unknown>;
  try { checkout = await api.payments.checkout({ reservationReference: reference }) as Record<string, unknown>; }
  catch { notFound(); }
  return <main className="grid min-h-svh place-items-center bg-muted/30 px-4 py-10"><section className="w-full max-w-xl rounded-3xl border border-border bg-card p-6 shadow-sm sm:p-9"><span className="inline-flex rounded-full bg-brand-green-100 px-3 py-1 text-xs font-semibold text-brand-green-900">Reservation secured</span><h1 className="mt-5 text-3xl font-bold tracking-tight">Complete your plot purchase</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Your reservation is held until {new Date(String(checkout.expiresAt)).toLocaleString()}. Payment must be submitted before that time.</p><div className="mt-7 grid gap-4 rounded-2xl border border-border p-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Estate</p><p className="mt-1 font-semibold">{String(checkout.estateName)}</p></div><div><p className="text-xs text-muted-foreground">Plot</p><p className="mt-1 font-semibold">{String(checkout.plotNumber)}</p></div><div><p className="text-xs text-muted-foreground">Reservation</p><p className="mt-1 font-mono text-sm font-semibold">{reference}</p></div><div><p className="text-xs text-muted-foreground">Amount due</p><p className="mt-1 font-semibold">GHS {Number(checkout.amount).toLocaleString()}</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><Link href={`/reservations/${reference}/payment`} className="inline-flex h-12 items-center justify-center rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground">Continue to payment</Link><Link href="/account/reservations" className="inline-flex h-12 items-center justify-center rounded-xl border border-border px-5 text-sm font-semibold">View reservations</Link></div><p className="mt-5 text-xs leading-5 text-muted-foreground">MVP payments are simulated. AsaseLink records the collection, an administrator verifies it, and the seller can request payout only after verification.</p></section></main>;
}
