import Link from "next/link";
import { notFound } from "next/navigation";
import { getServerApiClient } from "@/utils/server-orpc";

export default async function ReservationCreatedPage({ params }: { params: Promise<{ reference: string }> }) {
  const { reference } = await params;
  const api = await getServerApiClient();
  let checkout: Record<string, unknown>;
  try { checkout = await api.payments.checkout({ reservationReference: reference }) as Record<string, unknown>; }
  catch { notFound(); }
  const isHold = checkout.reservationType === "PAID_HOLD";
  return <main className="grid min-h-svh place-items-center bg-muted/30 px-4 py-10"><section className="w-full max-w-xl rounded-3xl border border-border bg-card p-6 shadow-sm sm:p-9"><span className="inline-flex rounded-full bg-brand-green-100 px-3 py-1 text-xs font-semibold text-brand-green-900">{isHold ? "Hold payment window open" : "Checkout lock secured"}</span><h1 className="mt-5 text-3xl font-bold tracking-tight">{isHold ? "Pay the hold fee" : "Complete your plot purchase"}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">This temporary lock expires at {new Date(String(checkout.expiresAt)).toLocaleString("en-GH")}. The server expiry remains authoritative.</p><div className="mt-7 grid gap-4 rounded-2xl border border-border p-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Estate</p><p className="mt-1 font-semibold">{String(checkout.estateName)}</p></div><div><p className="text-xs text-muted-foreground">Plot</p><p className="mt-1 font-semibold">{String(checkout.plotNumber)}</p></div><div><p className="text-xs text-muted-foreground">Reservation</p><p className="mt-1 font-mono text-sm font-semibold">{reference}</p></div><div><p className="text-xs text-muted-foreground">{isHold ? "Hold fee" : "Amount due"}</p><p className="mt-1 font-semibold">GHS {Number(checkout.amount).toLocaleString()}</p></div>{isHold ? <div className="sm:col-span-2"><p className="text-xs text-muted-foreground">Refund if hold expires</p><p className="mt-1 font-semibold">GHS {Number(checkout.refundableAmount).toLocaleString()}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{String(checkout.terms)}</p></div> : null}</div><div className="mt-7 grid gap-3 sm:grid-cols-2"><Link href={`/reservations/${reference}/payment`} className="inline-flex h-12 items-center justify-center rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground">{isHold ? "Pay hold fee" : "Continue to payment"}</Link><Link href="/account/reservations" className="inline-flex h-12 items-center justify-center rounded-xl border border-border px-5 text-sm font-semibold">View reservations</Link></div><p className="mt-5 text-xs leading-5 text-muted-foreground">MVP payments are simulated. AsaseLink records the collection and an administrator verifies it before the reservation changes state.</p></section></main>;
}
